### ISSUE TITLE
Unpausing a level with spacebar causes the player to jump

### ISSUE THREAD

**Issue by matcool** [geode-sdk/CustomKeybinds#1]
Unpausing the pause menu with the spacebar causes the space input to go through, and starts holding as if you had clicked.

The vanilla behavior is to uh not do this, and i think it is much preferred because this just ends up causing a surprised jump for the player

**Comment by matcool** [comment]
not fixed! oops

**Comment by altalk23** [comment]
fixed in d997c75 instead
