### ISSUE TITLE
Add support for mouse button inputs

### ISSUE THREAD

**Issue by Flyingturtle215** [geode-sdk/CustomKeybinds#12]
I would like to use my right mouse button as a jump input, but the mod does not allow for mouse buttons to be added. If it is possible, mouse buttons as inputs would be a nice addition.

**Comment by Vantropix** [comment]
i've been missing this since the release of 2.2 without megahack, would love to see this again since i used mouse 4 for copy + paste and mouse 5 for deselect, i've had to get used to different binds and i'm still slower.
would love this feature!

**Comment by HJfod** [comment]
Support for the side mouse buttons have been added in the latest release!

We are still discussing whether to add support for left/right/middle clicks. I'm personally against it, as those are usually really context-sensitive with very specific purposes that you wouldn't assign other keys to. For example you would likely want to pan around the screen by holding middle click, but you likely would never want to pan around by holding `Ctrl + F` while moving the mouse. Imo left/right/middle clicking should just be exposed as APIs that mods can then hardcode assignments to
