### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by necocat0918** [geode-sdk/CustomKeybinds#15]
![20240209113737_1](https://github.com/geode-sdk/CustomKeybinds/assets/120387312/f5b2087a-2814-4f57-8097-91adbad8c25b)
The mod doesn't load, I tried to reinstall the mod but still not working

**Comment by Se1d228** [comment]
Same

**Comment by Se1d228** [comment]
I FOUND SOLUTION! Just download new installer and install geode again. Betas aren't updating in-game.

**Comment by Cvolton** [comment]
Auto updater is broken on Geode beta 13 and older, if you are on any of these versions, re-download the Geode installer and install Geode again to get the latest version

**Comment by necocat0918** [comment]
I'll try

**Comment by matcool** [comment]
update ur geode
