### ISSUE TITLE
buffering a click out of a checkpoint using the W key doesn't work

### ISSUE THREAD

**Issue by midiidev** [geode-sdk/CustomKeybinds#16]
attempting to buffer a click while dead in practice mode will not result in a jump when you respawn. it does work with mouse, but just not the W key. this is not an issue in the vanilla game or without this mod

**Comment by midiidev** [comment]
this also includes the spacebar and up arrow. only the mouse works for buffering out of a practice death

**Comment by FitPinguino** [comment]
same happens to me, its so annoying

**Comment by Aktimoose** [comment]
this happens to me at the beginning of normal mode attempts too

**Comment by matcool** [comment]
fixed in 1.5.1
