### ISSUE TITLE
ERROR_PORC_NOT_FOUND

### ISSUE THREAD

**Issue by RandomInsultedCoder** [geode-sdk/CustomKeybinds#25]
![Ekrano kopija 2024-02-16 211345](https://github.com/geode-sdk/CustomKeybinds/assets/109095551/f615d976-a1f3-416d-bf5a-13732fa36866)
It is broken.

**Comment by Kingminer7** [comment]
idk if this helps but its in FAQ
![Screenshot_20240225_083558_Discord](https://github.com/geode-sdk/CustomKeybinds/assets/100500023/99a629da-fc90-419c-85a7-78a52d547a80)
