### ISSUE TITLE
Since the owner of globed plans to release globed on mobile add mobile support (even if it doesn't give custom keybinds just do it as a fix)

### ISSUE THREAD

**Issue by SmallLSplash** [geode-sdk/CustomKeybinds#26]
This is gonna help some android players when globes does release on mobile

**Comment by TheSillyDoggo** [comment]
We already have platform dependant dependencys

**Comment by matcool** [comment]
since beta.18 customkeybinds could actually be used on android: https://github.com/geode-sdk/geode/pull/507, but yes platform specific deps also exist
