### ISSUE TITLE
Search bar crashes the game

### ISSUE THREAD

**Issue by abeljakowoff** [geode-sdk/CustomKeybinds#28]
When I start to type something in search bar, **game crashes instantly**.

Attaching my crash log: [2024-02-19_12-09-08.log](https://github.com/geode-sdk/CustomKeybinds/files/14328931/2024-02-19_12-09-08.log)
![image](https://github.com/geode-sdk/CustomKeybinds/assets/70239841/922e526c-bdc8-4e75-bfa2-e0afbaf47c7d)

**Comment by SpectralMorphy** [comment]
Experiencing same issue now. This did not appear for me about a week before, probably came with last update.
[2024-03-25_12-25-24.log](https://github.com/geode-sdk/CustomKeybinds/files/14741479/2024-03-25_12-25-24.log)
![image](https://github.com/geode-sdk/CustomKeybinds/assets/75124358/9eaecfcc-c7bb-45ec-8cc0-dbbf37e68416)

**Comment by SpectralMorphy** [comment]
Yea, seems fixed now, thank you!
But it worked only after I uninstalled and installed the mod again.

**Comment by Fleeym** [comment]
cool, cool, then it probably was an update. i'm gonna close the thread now. thanks for the response, and sorry for being slow :)
