### ISSUE TITLE
Randomly starts double clicking, triple clicking, or even more clicks.

### ISSUE THREAD

**Issue by owrnp** [geode-sdk/CustomKeybinds#3]
Whenever i play a level, exit it, and play a different one, it starts to do double clicks but only with the keyboard, the mouse remains the same, this can multiply if you exit and join multiple times.

**Comment by altalk23** [comment]
megahack bug, should be uglily fixed by us with the 565d5f8 commit

**Comment by altalk23** [comment]
nvm its d997c75 instead
