### ISSUE TITLE
Hold to undo/redo does not work

### ISSUE THREAD

**Issue by sSolsta** [geode-sdk/CustomKeybinds#32]
2.2 added a feature where you can hold ctrl+z/ctrl+shift+z to undo/redo multiple actions in the editor (this is useful when you accidentally swipe a ton of objects across what you're building), but this does not work when CustomKeybinds is enabled.

**Comment by sSolsta** [comment]
I have been toldf that you have to manually enable it and modify the timing. why is it not enabled by default when it's in vanilla 2.2

**Comment by Fleeym** [comment]
this should be done by default now, closing the thread
