### ISSUE TITLE
Modifier keys can cause buttons to become held down

### ISSUE THREAD

**Issue by funwolf7** [geode-sdk/CustomKeybinds#33]
If you press a button, hold down a modifier key, then release the button, the button will act like it is held down until it is pressed again. This only happens with the custom keybinds mod enabled.

Example: in the editor, select an object, press w, press shift, release w, release shift. The object will begin to move upwards until w is pressed again or the escape menu is opened.

**Comment by SpeedNintendo** [comment]
omg furry, also +1 I've been experiencing this issue a lot as well, it's killed me a lot lol

adhd+tourette's has me pressing random buttons without knowing it sometimes (ex: ctrl) during levels, so all of a sudden boom I'm dead. So yea hopefully this gets fixed soon lol

**Comment by Fleeym** [comment]
Hey there, this will be fixed in the next release, I'll let you know when it's out

**Comment by Fleeym** [comment]
Fixed in 1.5.3

**Comment by Aibyou** [comment]
This issue has not been fixed at least not fully because keys can still become held in platformer mode
