### ISSUE TITLE
Cannot die to spikes in editor playtest

### ISSUE THREAD

**Issue by thebigcheese192** [geode-sdk/CustomKeybinds#35]
In editor playtest you cannot die to anything that has a red damage hitbox.
You also can't die from falling upwards out of the level.
Yes, this is custom keybinds, I checked.

**Comment by thebigcheese192** [comment]
![image](https://github.com/geode-sdk/CustomKeybinds/assets/159853519/81c989eb-e5be-4293-b54e-35942009fbb3)
example of the bug

**Comment by Alphalaneous** [comment]
This is a globed bug

**Comment by thebigcheese192** [comment]
> This is a globed bug

yea i realized
