### ISSUE TITLE
Custom Keybinds lets you stack the exit confirmation window

### ISSUE THREAD

**Issue by Nebularzz** [geode-sdk/CustomKeybinds#36]
This can also cause a crash.

Recreation steps:
1. Enable exit confirmation
2. Press: ESC, ESC, Space, ESC, ESC
Now 2 windows are stacked.
You can continue stacking by pressing: Space, ESC, ESC

Next up to cause the segfault, you need to:
1. Click and hold exit.
2. Hold Space.
3. Press ESC.
4. Release holding exit.

The game should crash now.
If it doesn't, give it another try.

Another it could crash by stacking windows, is to just spam closing the windows with cancel. This is a lot less likely to crash though, and is pretty much random.

https://github.com/geode-sdk/CustomKeybinds/assets/103582504/274fa36e-35ac-409c-b5b8-c07a0d13818c

**Comment by Aktimoose** [comment]
The main issue here is that unpausing while the Confirm Exit menu is on at all is possible. Every issue listed here appears to result from that.

Behaviour with the mod (and nothing else): 

https://github.com/geode-sdk/CustomKeybinds/assets/44620677/8e177bad-7cee-49aa-bbf3-21c28ea00092



Behaviour in vanilla:

https://github.com/geode-sdk/CustomKeybinds/assets/44620677/c0323fa7-ad86-45d1-87ac-16857b80f9ea

**Comment by Fleeym** [comment]
Hey there, sorry for the late response, I got around to checking this, fixed in the next release, will let you know when it's out :)

**Comment by Fleeym** [comment]
Fixed in v1.5.3

**Comment by Aktimoose** [comment]
The window stacking bug appears to be fixed in 1.5.3, but the Confirm Exit unpause behaviour still isn't identical to Vanilla. Pressing space twice while the confirm exit window is up unpauses it, while in vanilla it shouldn't ever unpause the game in that state.

**Comment by Fleeym** [comment]
Ah, I understand, I'll make it cancel out the action if the popup is present

**Comment by Fleeym** [comment]
v1.5.4 now replicates the vanilla behaviour (it's a bit of a hacky fix, do let me know if it still does anything bad)
