### ISSUE TITLE
Music continues if you restart on a StartPos and pressing restart deletes music

### ISSUE THREAD

**Issue by Ev212** [geode-sdk/CustomKeybinds#37]
If you use a startpos and die the song will continue instead of restarting and if press the restart button on the pause menu the song will disappear

**Comment by Fleeym** [comment]
Hey there, I can't seem to reproduce this, can you try getting the bug with only custom keybinds installed?

**Comment by Ev212** [comment]
sure

**Comment by Ev212** [comment]
ill make a video

**Comment by Fleeym** [comment]
make sure you are on the latest version before doing so (1.5.2)

**Comment by Ev212** [comment]
also i confirmed its custom keybinds as i removed every mod and tried

**Comment by Ev212** [comment]
also i cant upload the video because its too big

**Comment by Ev212** [comment]
can i put like a yt link?

**Comment by Fleeym** [comment]
sure

**Comment by Ev212** [comment]
ok heres the link
https://youtu.be/hPWLMUdSbrM

**Comment by Fleeym** [comment]
this might be an incompatibility with some other mod you have enabled, I can't replicate it myself

**Comment by Ev212** [comment]
ok yea it was an incompatibility
i will close it now

**Comment by Ev212** [comment]
ok
