### ISSUE TITLE
using a button for moving, rotating, etc an object in the editor will infinitely recursively repeat that action

### ISSUE THREAD

**Issue by ChadNarukami** [geode-sdk/CustomKeybinds#42]
If I were to place a block, then hit W, the block would go up one grid space once, then the w key press would infinitely repeat. this only happened after I updated to the latest version of the mod.

**Comment by Fleeym** [comment]
Looking into it

**Comment by Fleeym** [comment]
fixed in 1.5.4, sorry!

**Comment by ChadNarukami** [comment]
> fixed in 1.5.4, sorry!

Cool, thanks!
