### ISSUE TITLE
Controller Keybinds do not work

### ISSUE THREAD

**Issue by BestSpark687090** [geode-sdk/CustomKeybinds#49]
I am using a Backbone controller which is being picked up by the computer as an Xbox 360 controller. When I enable Custom Keybinds, the controller does something where when I hold an input when the level starts, the game holds those inputs until I quit the level.  When I disable the mod, the controller works as expected. My controls are also set as default.
If you could fix this, it would be kindly appreciated.
Thank you.

**Comment by Cvolton** [comment]
if you have click between frames installed, that mod breaks controller support
