### ISSUE TITLE
If I hold jump my CPS spikes up to like 12

### ISSUE THREAD

**Issue by MarioMastr** [geode-sdk/CustomKeybinds#5]
video for example, cps in very top right measured by crystal client

https://github.com/geode-sdk/CustomKeybinds/assets/84964352/19bc9ca5-9654-4ff1-ad85-299695b31fd6

**Comment by ninXout** [comment]
This is an issue with `geode.custom-keybinds`, please remove it from your mods folder for the time being until fixed

**Comment by MarioMastr** [comment]
i will, but let me just say: i know that is is an issue with geode.custom-keybinds, that's why im reporting it on the repo for geode.custom-keybinds

**Comment by altalk23** [comment]
@ninXout hi did you forget to call dtor on UILayer :trollface:

**Comment by AshPikachu1** [comment]
issue still seems to persist, using k and l keys for p1 jump and reaching 30 cps just by holding

**Comment by Fleeym** [comment]
i'll look into it

**Comment by Fleeym** [comment]
check if the bug repeats on v1.3.1, should be fixed

**Comment by AshPikachu1** [comment]
fixed tysm

**Comment by Fleeym** [comment]
cool, i can close this now
