### ISSUE TITLE
when auto retry is off, pressing space to restart doesnt work

### ISSUE THREAD

**Issue by RedYoshi123** [geode-sdk/CustomKeybinds#54]
pressing space when auto retry is off after you die, wont restart the level like it is supposed to.

**Comment by cycle00** [comment]
reproduced the issue

**Comment by cameronaw13** [comment]
affects my client as well

**Comment by xparadoxical** [comment]
this is an issue both on the retry screen and the level complete screen

**Comment by HungryElmo** [comment]
I have this same issue, anyone find a fix yet?

**Comment by xparadoxical** [comment]
in v1.6.3 space bar completely doesn't work in either of the 3 menus
