### ISSUE TITLE
Restart keybind works in situations where it should be disabled

### ISSUE THREAD

**Issue by cameronaw13** [geode-sdk/CustomKeybinds#56]
The restart keybind still works on the practice/level complete screen, allowing the player to continue playing the level with the complete screen shown on top. Disabling the keybind during the endscreen to be consistent with vanilla gd would solve this issue.

**Comment by cameronaw13** [comment]
Edit: It seems that not only does the issue persist on v1.6.2, but it also can occur when on the pause screen after further testing.

**Comment by xparadoxical** [comment]
you can easily see this by pausing, opening settings and pressing R - the settings menu stays open

**Comment by xparadoxical** [comment]
it's almost completely fixed now, except for R / Ctrl+R in pause menu

**Comment by Cvolton** [comment]
Odd, I couldn't reproduce that myself, will look into it again though

The old update also had r/Ctrl+r in pause menu as an explicit feature, this has also been removed now to align more with the vanilla behavior

**Comment by xparadoxical** [comment]
fixed in v1.6.4

**Comment by cameronaw13** [comment]
fixed on my end as well, ty!
