### ISSUE TITLE
Spacebar doesn't work on in-level menus

### ISSUE THREAD

**Issue by xparadoxical** [geode-sdk/CustomKeybinds#59]
While in a level, spacebar is used in menus for restarting from a retry screen or level complete screen, and for continuing from the pause screen. With Custom Keybinds that's not the case.

**Comment by iyuashi** [comment]
i agree, although while pausing the level, space key DOES work to resume, it DOES NOT work to retry once you die, due to this issue i have been suffering from auto-retry 😭

**Comment by xparadoxical** [comment]
> space key DOES work to resume
not for me

**Comment by iyuashi** [comment]
you are completely right, with this new update, it no longer works for resume either, big rip lmao

**Comment by xparadoxical** [comment]
I have dementia or severe sleep deprivation, this is a dupe of #54 which I literally looked at earlier
