### ISSUE TITLE
Impostor PlayLayer crashes or causes double taps

### ISSUE THREAD

**Issue by Cvolton** [geode-sdk/CustomKeybinds#6]
Pressing space/play during the fade in into LevelInfoLayer causes a PlayLayer to get initialized but it never gets faded into (this is a RobTop bug). This causes the following bugs in combination with Custom Keybinds:
* Exiting LevelInfoLayer (I went into CreatorLayer in this example) and pressing space causes the game to crash. See attached crashlog: [2023-10-20_21-40-22.log](https://github.com/geode-sdk/CustomKeybinds/files/13058059/2023-10-20_21-40-22.log) (the actual crash appears to be 2nd in the file)
* Entering a valid PlayLayer avoids the crash but it causes the double tap issue

**Comment by Fleeym** [comment]
uhh this is fixed ig
