### ISSUE TITLE
spacebar to unpause doesn't work anymore in latest update

### ISSUE THREAD

**Issue by JerichoGesolgani** [geode-sdk/CustomKeybinds#60]
this new update broke my spacebar to unpause the fucking level even when i put "space" in unpause level option the shit do not fucking work also regardless what key i set to unpause (e.g. uparrow) the level in option menu it's doesn't do anything please fix it QUICK!!!

**Comment by Master3499** [comment]
i'm having the same issue, pressing space does not unpause the level or restart the level after hitting the endscreen
pressing space does work for opening a level and for the player input, but not for unpausing/restarting

**Comment by escapethebackroomser** [comment]
yeah. same.
