### ISSUE TITLE
can't add click as a key

### ISSUE THREAD

**Issue by R3Ked** [geode-sdk/CustomKeybinds#70]
for some reason custom keybinds doesn't have click as a default for p1 jump so i went to add it but i can't. it just doesn't show up at all. i can press other keys and they work fine but not click. why

**Comment by matcool** [comment]
because clicking is not a key to customkeybinds

**Comment by R3Ked** [comment]
ok but i can't click to jump with this on

**Comment by matcool** [comment]
customkeybinds does not interfere with playing the game with your mouse

**Comment by Quadragintillion** [comment]
@matcool yes it does

**Comment by Quadragintillion** [comment]
@R3Ked I was having the same issue, it's actually CBF, which happens to depend on this mod, so when you disable this mod it also disables CBF, making it seem like the issue is this mod
