### ISSUE TITLE
Player inputs don't  work on Linux

### ISSUE THREAD

**Issue by Krepppa352** [geode-sdk/CustomKeybinds#73]
I just installed Arch Linux yesterday and wanted to use Click Between frames. Installed it, restarted, player inputs don't work.
I disabled Custom Keybinds and everything worked fine, though Click Between Frames depends on this. I saw someone else on Pop!_OS on the issues page of CBF having this same problem.
Sadly I have no ieda what could be causing the issue, just wanted to tell y'all about it.

**Comment by dankmeme01** [comment]
this is most likely an issue with CBF, not custom keybinds. 

for CBF to work on Linux, you need to add your user to the `input` group (which can be done with `sudo usermod -aG input $USER` and restart your system.

**Comment by Krepppa352** [comment]
Oh, okay. Thank you so mucj for the quick answer :))
