### ISSUE TITLE
Custom Keybinds makes it impossible to play with keyboard (space, up arrow) on Linux (through Steam/Proton)

### ISSUE THREAD

**Issue by HGStyle** [geode-sdk/CustomKeybinds#78]
Installing some mods made me unable to play with any key of my keyboard on Geode. After some random uninstallations and stuff, I got thinkinh it comes all from this mod, as Prism Menu doesn't have a depency on that mod and it works, but any other mod that I install which depends on that mod makes my keyboard completely useless and I can only play with the mouse (which I'm terrible at).

NOTE: CBF also seems to make some trouble with inputs, but uninstalling it makes me still have this bug.

Hardware/software:
ZorinOS 17.2 (based on Ubuntu) with Steam, Geometry Dash (official version) 2.2074 through Proton 9.0-3

**Comment by matcool** [comment]
check your binds, they mightve reset

**Comment by OmriPH** [comment]
same

**Comment by HGStyle** [comment]
> check your binds, they mightve reset

Looks like they were, thanks and sorry for asking, didn't knew I could customize them (I though Custom Keybinds was an API for adding keybinds for other mods...)
