### ISSUE TITLE
Can't bind to Escape

### ISSUE THREAD

**Issue by SUSDogus** [geode-sdk/CustomKeybinds#81]
I can't bind "Pause Level" to escape, so to exit a level I have to close the game.

**Comment by Cvolton** [comment]
escape is one of the few keys that can't be set because it's always bound to "back" 

this means that inside a level it is bound to pause regardless of your settings in custom keybinds - the pause level keybind allows you to set another key on top of that, but escape specifically is unchangable

**Comment by SUSDogus** [comment]
Well it stopped working for me

**Comment by SUSDogus** [comment]
New update fixed this
