### ISSUE TITLE
Using the Esc key to pause the game either does nothing or crashes.

### ISSUE THREAD

**Issue by CoderQCFromScraatch** [geode-sdk/CustomKeybinds#9]
https://github.com/geode-sdk/CustomKeybinds/assets/73763394/1bbe7999-97d4-44cf-89f6-5e1d1e3c4fc7

---------------------------
Geometry Dash Crashed
---------------------------
2024-01-27T19:43:05-0800
Whoopsies! An unhandled exception has occured.

== Geode Information ==
Loader Version: v2.0.0-beta.11
Loader Commit: 231a7c2
Bindings Commit: eb61557
Installed mods: 18
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00A2F9C0 (GeometryDash.exe + 3bf9c0)
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3bf9c0
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3bf943
 - 1CC00216
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 1f178 (keybinds::DeviceEvent::wasDetached + 32184)
 - 1CC00037
 - 1CC00A66
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 22364 (keybinds::DeviceEvent::wasDetached + 44964)
 - 1CC0088F
 - 1CC0088F
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c7841 (cocos2d::CCEGLView::onGLFWKeyCallback + 481)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 116c7e (cocos2d::CCPoint::unrotate + 7998)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 1185d6 (cocos2d::CCPoint::unrotate + 14486)
 - C:\Windows\System32\USER32.dll + 4120b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 381ca (GetClassLongW + 1978)
 - C:\Windows\System32\USER32.dll + 37897 (GetSystemMetricsForDpi + 5959)
 - C:\Windows\System32\USER32.dll + 35a3b (CallWindowProcW + 27)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
 - C:\Windows\System32\USER32.dll + 4120b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 381ca (GetClassLongW + 1978)
 - C:\Windows\System32\USER32.dll + 35f2a (DispatchMessageW + 586)
 - C:\Windows\System32\USER32.dll + 35cf0 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 83090 (OverlayHookD3D3 + 121824)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c5976 (geode::utils::web::AsyncWebRequest::userAgent + 9446)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 3f800000
EBX: 1ffd8138
ECX: 1ffd8024
EDX: 00000001
EBP: 005ff350
ESP: 005ff328
EDI: 0000001b
ESI: 1ffd8024
EIP: 00a2f9c0

== Installed Mods ==
x | [v2.1.5] fleym.nongd
x | [v2.0.0-beta.11] geode.loader
x | [v1.2.13] gdutilsdevs.gdutils
x | [v1.1.2] alphalaneous.projectedstars
  | [v1.2.2] firee.PrismMenu
  | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.0.1] coderqc.gdswearfilter
x | [v1.0.1] itzkiba.grandpa_demon
x | [v4.0.0-alpha.9] cvolton.betterinfo
x | [v1.2.4] geode.custom-keybinds
x | [v1.0.1] hjfod.gmd-api
x | [v1.4.0] geode.devtools
  | [v1.6.0] prevter.openhack
x | [v1.1.4] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.0.4] hjfod.gdshare
  | [v2.1.0] TheSillyDoggo.GradientPages
x | [v1.0.12] zilko.xdbot

---------------------------
OK   
---------------------------

**Comment by Fleeym** [comment]
should be fixed in the latest release
